{"name": "Проверка сообщения: Неверные учетные данные пользователя при неуспешной авторизации с неверным логином", "status": "passed", "parameters": [{"name": "login", "value": "'admin1'"}, {"name": "password", "value": "'zj#KqU1'"}], "start": 1654298783251, "stop": 1654298786623, "uuid": "aaaf14ee-b131-48d8-bbd6-e3ef05e9561d", "historyId": "9992b21df466c431e2cc6128c73853f7", "testCaseId": "14560c4f734ab761fabde47b607f8dc8", "fullName": "Tests.test_autorization#test_wrong_login", "labels": [{"name": "severity", "value": "minor"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_autorization"}, {"name": "host", "value": "DESKTOP-13RCMAF"}, {"name": "thread", "value": "13272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_autorization"}]}